env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/Jmainguy/k8snodeissues
  description: Designed to point out potential issues in a kubernetes node. Such as pods stuck terminating, or pending.
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  formats:
  - deb
  - rpm

brews:
  - tap:
      owner: Jmainguy
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Jmainguy/k8snodeissues
    description: Designed to point out potential issues in a kubernetes node. Such as pods stuck terminating, or pending.
    license: "GPL-2.0"
    commit_author:
      name: Jonathan Seth Mainguy
      email: jon@soh.re
    test: |
      system "#{bin}/k8snodeissues"
    install: |
      bin.install "k8snodeissues"

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
