language: go
addons:
  apt:
    packages:
    - rpm
env:
  matrix:
  - GO111MODULE="on"
  global:
    secure: mbY2QPRc/5uLewmhk5N1+NJfiFdcvxbzXegrNsWhzdC+dojBYPgCtQuRs/MJGoNAtmCHyq6CEOftcyaOaiPxviKG/rvuQWRBVyDFgioXfjaEEfnWElXWhbOKn3opxC1ApKMbMju3JJZ3rAeVKDIoCzjat19Qc8eDtuNil7xW87eiKwXrnQ8f8e57jX4r62I+2LcGu11BTz3xwl7ynUg2xXkJTjbWx9t50duIJp5ovMnUQz0bCIIMaFQqJQdcNZmRShdb8Bn5T98+Ka6qU+9WhtoFK+I0MVYPWbKaIGqySqDtSrKY2OtMugQLjWS4KN5+mCYyT1pLV7mheFwU80fvsoL85mFqYPqh25h5ZySOZxAIV2h+dvXVSkfpjFRdAi4QEh+nVrXzLpX2GdOCmLfuIOJ3Pi5cRhUSv47Fl8uhUEt/jSyVhCCM4+y9oOAYic19LH94KQ5AKEwKMOs6sr3YWAK9MEUj1Lmu+SGWJUiDvULqiWbtbm1cxasX/8ODIsnCs8x56nGFkb7AoLTTmezGWrUcUWrplsurE0oJQZhX1o4ll9DMKZEHqNYnw870bQ0zjujSbDTipp4UdpBQ7x2/VITrAVBEJ4aiECk8Ifj9Ta6u94aOejyQxJznI1h4szXMYNx60xSSm4MbxNeZ1/ZqquUlax2pL8kjkUWhpVyR8nE=
install: 
after_success: 
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
after_deploy:
  - ./after_deploy.sh
